# Generated by Django 2.1.4 on 2019-02-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fq_fq_type_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FQ',
        ),
        migrations.DeleteModel(
            name='FQ_type',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
